experiment:
  exp_name: fno_baseline

paths:
  savepath_train: /kaggle/temp/data/train/
  savepath_val: /kaggle/temp/data/val/
  save_dir: /kaggle/working/log.json
  model_save_path: /kaggle/working/fno_baseline.pt
  stats_path: /kaggle/working/grid_robust_stats.npy
  topo_path: /kaggle/working/topo_proxy.npy

data:
  time_input: 10
  time_out: 16
  S1: 140
  S2: 124
  total_time: 26
  stride: 4

features:
  V: 17
  met_variables: ["cpm25", "t2", "u10", "v10", "swdown", "pblh", "rain"]
  emission_variables:
    ["PM25", "NH3", "SO2", "NOx", "NMVOC_e", "NMVOC_finn", "bio"]
  derived_variables: ["wind_speed", "vent_coef", "rain_mask"]

model:
  modes: 8
  width: 192

training:
  batch_size: 16
  epochs: 80
  lr: 0.000782
  weight_decay: 0.000076
  checkpoint_every: 10
  save_checkpoint: True
  early_stopping: False
